DROP DATABASE IF EXISTS ShoppingsAPI;
DROP DATABASE IF EXISTS prueba;

CREATE DATABASE IF NOT EXISTS ShoppingsAPI;

USE ShoppingsAPI;

CREATE TABLE IF NOT EXISTS users(
    Id MEDIUMINT NOT NULL AUTO_INCREMENT,
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL,
    DNI INT(2) NOT NULL,
    Birthdate DATE NOT NULL,
    Sex VARCHAR(20),
    Password VARCHAR(255) ,
    Email VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID),
    UNIQUE(Email,DNI)
    
);
DROP DATABASE IF EXISTS Shopping;

USE ShoppingsAPI;

CREATE TABLE IF NOT EXISTS Shopping(
    shopping_Id MEDIUMINT NOT NULL AUTO_INCREMENT,
    ShoppingName VARCHAR(255) NOT NULL,
    Manager VARCHAR(255) NOT NULL,
    latLng INT(2) NOT NULL,
    Cuit VARCHAR(50) NOT NULL UNIQUE,
    PRIMARY KEY(shopping_Id),
    UNIQUE(Cuit)
    
);

DROP DATABASE IF EXISTS Store;
USE ShoppingsAPI;

CREATE TABLE IF NOT EXISTS Store(
    Id MEDIUMINT NOT NULL AUTO_INCREMENT,
    StoreName VARCHAR(255) NOT NULL,
    Manager VARCHAR(255) NOT NULL,
    Cuit VARCHAR(50) NOT NULL UNIQUE,
    shopping_Id  MEDIUMINT NOT NULL,
    PRIMARY KEY(Id),
    FOREIGN KEY (shopping_Id) REFERENCES Shopping(shopping_Id) ON DELETE CASCADE
    
    
);